CC=gcc

cmake_minimum_required(VERSION 3.21)
project(HOMEWORK_01)

set(CMAKE_C_STANDARD 99)

include_directories(.)

add_executable(
        main.c 
        alloc.c
        alloc.h
        matrix.h
        mult.c
        mult.h
        print.c
        print.h
        read.c
        read.h)
